/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

/**
 *
 * @author Nini
 */
public class CustomerAccountPage extends javax.swing.JFrame {

    private String accountName = "";

    /**
     * Creates new form CustomerAccountPage
     */
    public CustomerAccountPage() {
        initComponents();
    }

    public CustomerAccountPage(String str) {
        accountName = str;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        detailsScroll = new javax.swing.JScrollPane();
        detailsText = new javax.swing.JTextArea();
        transScroll = new javax.swing.JScrollPane();
        transactionHistory = new javax.swing.JTable();
        debtLabel = new javax.swing.JLabel();
        debtAmount = new javax.swing.JTextField();
        searchField = new javax.swing.JTextField();
        submitSearch = new javax.swing.JButton();
        titleScroll = new javax.swing.JScrollPane();
        titleArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LIMS 2000: Customer Account");
        setPreferredSize(new java.awt.Dimension(615, 530));

        detailsText.setEditable(false);
        detailsText.setColumns(20);
        detailsText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        detailsText.setRows(5);
        detailsText.setText("Account Details\n\nAccount Number:000542369\n\nName:"+accountName+"\n\nE-mail:"+accountName+"@gmail.com\n\n"+
                            "Address:4578 N. Shortbranch Rd. Mahogony, AL 36425\n\nAccount Status: active");
        detailsScroll.setViewportView(detailsText);

        transScroll.setToolTipText("Transaction History");
        transScroll.setViewportBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        transactionHistory.setBackground(new java.awt.Color(204, 204, 204));
        transactionHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Transcation Number", "Book Title", "Due Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        transScroll.setViewportView(transactionHistory);
        if (transactionHistory.getColumnModel().getColumnCount() > 0) {
            transactionHistory.getColumnModel().getColumn(0).setResizable(false);
            transactionHistory.getColumnModel().getColumn(1).setResizable(false);
            transactionHistory.getColumnModel().getColumn(2).setResizable(false);
        }

        debtLabel.setText("Debt:");

        debtAmount.setEditable(false);
        debtAmount.setText("$0.00");

        searchField.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        searchField.setText("Please enter author, title, or ISBN...");
        searchField.setToolTipText("Searchbar");

        submitSearch.setText("Submit");
        submitSearch.setToolTipText("Submit search request");
        submitSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitSearchActionPerformed(evt);
            }
        });

        titleScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        titleScroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        titleArea.setEditable(false);
        titleArea.setColumns(20);
        titleArea.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        titleArea.setRows(2);
        titleArea.setTabSize(6);
        titleArea.setText("LIMS 2000: Customer Account");
        titleScroll.setViewportView(titleArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(transScroll)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(detailsScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleScroll, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(searchField)
                                .addComponent(submitSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(498, 498, 498)
                        .addComponent(debtLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(debtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(detailsScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(submitSearch)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(debtLabel)
                            .addComponent(debtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(transScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitSearchActionPerformed
        this.dispose();
        new SearchPage().setVisible(true);
    }//GEN-LAST:event_submitSearchActionPerformed

    public static void load() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerAccountPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerAccountPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerAccountPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerAccountPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerAccountPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField debtAmount;
    private javax.swing.JLabel debtLabel;
    private javax.swing.JScrollPane detailsScroll;
    private javax.swing.JTextArea detailsText;
    private javax.swing.JTextField searchField;
    private javax.swing.JButton submitSearch;
    private javax.swing.JTextArea titleArea;
    private javax.swing.JScrollPane titleScroll;
    private javax.swing.JScrollPane transScroll;
    private javax.swing.JTable transactionHistory;
    // End of variables declaration//GEN-END:variables
}
